esphome:
  name: my-mini-voice-assistant
  friendly_name: My Mini Voice Assistant
  on_boot:
    - priority: 1
      then:
        - voice_assistant.stop:
        - delay: 500ms
        - micro_wake_word.start:

esp32:
  variant: esp32c3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHMODE_DIO: y
  flash_size: 16MB

# Enable Home Assistant API
api:
  encryption:
    key: !secret mini_voice_assistant_api

ota:
  - platform: esphome
    password: !secret mini_voice_assistant_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

substitutions:
  boot_btn_pin: GPIO09
  i2c_sda_pin: GPIO03
  i2c_scl_pin: GPIO04
  neopixel_pin: GPIO02
  i2s_ws_pin: GPIO06
  i2s_bck_pin: GPIO08
  i2s_mck_pin: GPIO10
  i2s_do_pin: GPIO05
  i2s_di_pin: GPIO07
  mute_pin: GPIO11

i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}

light:
  - platform: esp32_rmt_led_strip
    id: my_indicator
    chipset: ws2812
    num_leds: 1
    default_transition_length: 0s
    rgb_order: GRB
    name: "Indicator Light"
    restore_mode: ALWAYS_OFF
    pin: ${neopixel_pin}
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%


binary_sensor:
  - platform: gpio
    pin:
      number: ${boot_btn_pin}
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Boot Button"
    id: boot_btn
    on_click:
      then:
        - micro_wake_word.start:

output:
  - platform: gpio
    pin: ${mute_pin}
    id: mute_control
    inverted: true
#https://esphome.io/components/audio_dac/es8311/
audio_dac:
  - platform: es8311
    id: my_dac
    use_microphone: false
    bits_per_sample: 16bit
    #sample_rate: 48000
    sample_rate: 16000
    address: 0x18

#https://esphome.io/components/i2s_audio/
i2s_audio:
  - id: i2s_output
    i2s_lrclk_pin: ${i2s_ws_pin}
    i2s_bclk_pin: ${i2s_bck_pin}
    i2s_mclk_pin: ${i2s_mck_pin}

#https://esphome.io/components/speaker/i2s_audio/
speaker:
  - platform: i2s_audio
    id: my_speaker
    dac_type: external
    i2s_dout_pin: ${i2s_do_pin}
    i2s_audio_id: i2s_output
    #to be able to use it on memory restricted device (for testing)
    channel: mono
    #sample_rate: 48000
    sample_rate: 16000
    bits_per_channel: 16bit
    buffer_duration: 500ms


#https://esphome.io/components/microphone/i2s_audio/
microphone:
  - platform: i2s_audio
    id: external_mic
    adc_type: external
    i2s_din_pin: ${i2s_di_pin}
    i2s_audio_id: i2s_output

image:
  - file: mdi:emoticon
    id: smile
    type: binary
    resize: 40x40

media_player:
  - platform: speaker
    name: None
    id: my_media_player
    announcement_pipeline:
      speaker: my_speaker
      format: WAV
    codec_support_enabled: false
    buffer_size: 6000
    volume_min: 0.4
    files:
      - id: timer_finished_wave_file
        file: https://github.com/esphome/wake-word-voice-assistants/raw/main/sounds/timer_finished.wav
    on_announcement:
      - if:
          condition:
            - microphone.is_capturing:
          then:
            - script.execute: stop_wake_word
      - light.turn_on:
          id: my_indicator
          blue: 100%
          red: 0%
          green: 0%
          brightness: 100%
          effect: none
    on_idle:
      - script.execute: start_wake_word
      - script.execute: reset_led

switch:
  - platform: template
    id: timer_ringing
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_off:
      # Turn off the repeat mode and disable the pause between playlist items
      - lambda: |-
              id(my_media_player)
                ->make_call()
                .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_OFF)
                .set_announcement(true)
                .perform();
              id(my_media_player)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 0);
      # Stop playing the alarm
      - media_player.stop:
          announcement: true
    on_turn_on:
      # Turn on the repeat mode and pause for 1000 ms between playlist items/repeats
      - lambda: |-
            id(my_media_player)
              ->make_call()
              .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_ONE)
              .set_announcement(true)
              .perform();
            id(my_media_player)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 1000);
      - media_player.speaker.play_on_device_media_file:
          media_file: timer_finished_wave_file
          announcement: true
      - delay: 15min
      - switch.turn_off: timer_ringing

voice_assistant:
  id: va
  micro_wake_word:
  microphone:
    microphone: external_mic
    channels: 0
    gain_factor: 4
  media_player: my_media_player
  noise_suppression_level: 2
  auto_gain: 31dBFS
  on_listening:
    - light.turn_on:
        id: my_indicator
        blue: 100%
        red: 0%
        green: 0%
        effect: "Slow Pulse"
  on_stt_vad_end:
    - light.turn_on:
        id: my_indicator
        blue: 100%
        red: 0%
        green: 0%
        effect: "Fast Pulse"
  on_tts_start:
    - light.turn_on:
        id: my_indicator
        blue: 100%
        red: 0%
        green: 0%
        brightness: 100%
        effect: none
  on_end:
    # Handle the "nevermind" case where there is no announcement
    - wait_until:
        condition:
          - media_player.is_announcing:
        timeout: 0.5s
    - wait_until:
        - and:
            - not:
                voice_assistant.is_running:
            - not:
                speaker.is_playing:
    - lambda: id(va).set_use_wake_word(false);
    - micro_wake_word.start:
    - script.execute: reset_led
  on_error:
    - light.turn_on:
        id: my_indicator
        red: 100%
        green: 0%
        blue: 0%
        brightness: 100%
        effect: none
    - delay: 2s
    - script.execute: reset_led
  on_client_connected:
    - delay: 2s  # Give the api server time to settle
    - script.execute: start_wake_word
  on_client_disconnected:
    - script.execute: stop_wake_word
  on_timer_finished:
    - script.execute: stop_wake_word
    - wait_until:
        not:
          microphone.is_capturing:
    - switch.turn_on: timer_ringing
    - light.turn_on:
        id: my_indicator
        red: 0%
        green: 100%
        blue: 0%
        brightness: 100%
        effect: "Fast Pulse"
    - wait_until:
        - switch.is_off: timer_ringing
    - light.turn_off: my_indicator
    - switch.turn_off: timer_ringing

script:
  - id: reset_led
    then:
      - light.turn_on:
          id: my_indicator
          red: 0%
          green: 100%
          blue: 100%
          brightness: 60%
          effect: none
  - id: start_wake_word
    then:
      - if:
          condition:
            - not:
                - voice_assistant.is_running:
          then:
            - micro_wake_word.start:
  - id: stop_wake_word
    then:
      - micro_wake_word.stop:

#https://esphome.io/components/micro_wake_word/
micro_wake_word:
  microphone: external_mic
  on_wake_word_detected:
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
  vad:
  models:
    - model: okay_nabu

#https://esphome.io/components/display/ssd1306/
display:
  - platform: ssd1306_i2c
    id: my_display
    model: "SSD1306 128x64"
    address: 0x3C
    # this is just for this demo since all the code is doing showing a smiley face
    # on detecting microWakeWord
    auto_clear_enabled: false
